### ISSUE TITLE
Upstream devshell change broke Scala Native env variables

### ISSUE THREAD

**Issue by armanbilge** [typelevel/typelevel-nix#107]
I think this change:
- https://github.com/numtide/devshell/pull/257

broke our env variables:
https://github.com/typelevel/typelevel-nix/blob/a1f2cd62720f9043a4ad61363a06427c1e55f789/modules/native.nix#L24-L32

causing issues in:
- https://github.com/http4s/http4s/pull/7099

```
[http4s]$ echo $C_INCLUDE_PATH $LIBRARY_PATH 
/workspace/http4s/$DEVSHELL_DIR/include /workspace/http4s/$DEVSHELL_DIR/lib
```

**Comment by armanbilge** [comment]
- https://github.com/numtide/devshell/issues/258

**Comment by hnaderi** [comment]
I'm facing the same issue in several projects.

**Comment by rossabaker** [comment]
We could pin devshell while we wait for upstream to respond and still keep everything else fresh?
