### ISSUE TITLE
Additional maintainer(s)

### ISSUE THREAD

**Issue by rossabaker** [typelevel/typelevel-nix#15]
I like to have at least two maintainers on Typelevel projects.  This one shouldn't be too burdensome.  Volunteers?

**Comment by domenkozar** [comment]
As part of https://devenv.sh I added Scala tooling, maybe if you're interested it would be better to maintain it there?

https://github.com/cachix/devenv/pull/60

**Comment by rossabaker** [comment]
That's a neat project.  There's some nuance in supporting Scala:

- Which JDK does it build with?  Most libraries have one answer, most applications have another.
- Is Scala.js supported?
- Is Scala Native supported?  What libraries?
- There's a (declining) tradition of Jekyll sites that we support.

We handle all of that through configuration options.  Do you see the devenv language support modules as a starting point, or are you looking to keep them as simple booleans?

**Comment by domenkozar** [comment]
We now support a number of java versions: https://devenv.sh/reference/options/#languagesjavaenable

Probably scala should just enable java support as well?

Hopefully that answers your question around configuration options.

**Comment by rossabaker** [comment]
That answers my question about whether there's more than `languages.whatever.enable`.

We generally want our [sbt to have a specific JDK](https://github.com/typelevel/typelevel-nix/blob/322901710808b2703bd972a4ac6d11444b28a5c4/modules/typelevelShell.nix#L40), and having Scala Native support implies [at least two](https://github.com/typelevel/typelevel-nix/blob/322901710808b2703bd972a4ac6d11444b28a5c4/modules/native.nix#L19-L22), usually [three](https://github.com/typelevel/typelevel-nix/blob/322901710808b2703bd972a4ac6d11444b28a5c4/modules/native.nix#L13) extra packages.  The C support in devenv is `gcc`, and we need `clang`.

So I think that's all to say that it could work, but that to keep parity with what's here, the Scala config would need a lot more options.

**Comment by domenkozar** [comment]
I'm happy to move over maintenance if we get a list of the options we need for scala :)

**Comment by domenkozar** [comment]
@rossabaker I've made changes so that we add clang and `languages.scala.enable` now enables `languages.java.enable` where the SDK can be configured.

**Comment by domenkozar** [comment]
There should be proper propagation of jre package now: https://github.com/cachix/devenv/pull/309/files

**Comment by softinio** [comment]
> I like to have at least two maintainers on Typelevel projects. This one shouldn't be too burdensome. Volunteers?

Happy to volunteer to help with this one.

**Comment by samspills** [comment]
@softinio I have added you to to the Typelevel/nix team, thank you!

**Comment by rossabaker** [comment]
Thanks, @softinio!  Now that we're back to two-deep, closing this.

**Comment by softinio** [comment]
@samspills @rossabaker Thank you both!
