### ISSUE TITLE
Gate NodeJS support behind an option?

### ISSUE THREAD

**Issue by amesgen** [typelevel/typelevel-nix#2]
EDIT see next comment

---

Extremely minor nitpick: Currently, the default NodeJS version is printed unconditonally as part of the devshell MOTD:

https://github.com/rossabaker/typelevel-nix/blob/f0712172fcb658e2032deb771aec58e3c9f8a13c/modules/typelevelShell.nix#L53

For projects which do not require NodeJS this might be a bit confusing maybe?

**Comment by amesgen** [comment]
Ok I just saw that nodejs and yarn are added as packages unconditonally, so the scope of this issue should rather be to decide whether to put this behind an enable flag.

**Comment by rossabaker** [comment]
I had considered adding a flag.  I think it's a good idea.
